server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOSTNAME:localhost}:${MYSQL_PORT:3306}/TWITTER?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:welcome1}
  jpa:
    hibernate.ddl-auto: update
    show-sql: false

twitter:
  apiKey: "6bMIUFw5XtmsYeMem0L3S2pN9"
  apiSecret: "EfYKEHP82Q9BGfu2HQAvLumw6BoFS1xC5DKI18YPBhJkRTDmjm"
  accessToken: "1431209079184101379-Na8B5Gp1E2hFaXIxfQuWvDt5uFPcUK"
  accessTokenSecret: "sVYWERSSbxnWnil8ixqez6bf1jhaMoft5r5qkNkwDWvCE"



    